local SHOOT_INTERVAL = 0
local BULLET_SPEED = 4000
local PLAYER_SPEED = 500
local PLAYER_SIZE = 50

local M = {}

M.SHOOT_INTERVAL = SHOOT_INTERVAL
M.BULLET_SPEED = BULLET_SPEED
M.PLAYER_SPEED = PLAYER_SPEED
M.PLAYER_SIZE = PLAYER_SIZE

return M
